version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd hello-world-java
      - mvn install
      - aws s3 cp target/example-0.1.jar s3://lambda-func-buc
  post_build:
    commands:
      - echo Build completed on `date`
