version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd hello-world-java
      - sudo mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello-world-java/target/example-0.1.jar
